### ISSUE TITLE
Permission issues when using ansible user is non privileged

### ISSUE THREAD

**Issue by notetiene** [stefangweichinger/ansible-rclone#107]
When executing the role with non privilege user, several tasks fails because they lack privilege escalation.

The offending tasks are:
```yaml
- name: Create directory for ansible custom facts
  ansible.builtin.file:
    state: directory
    recurse: true
    path: /etc/ansible/facts.d

- name: Create facts file from template
  ansible.builtin.template:
    src: 'etc/ansible/facts.d/rclone.fact.j2'
    dest: /etc/ansible/facts.d/rclone.fact
    mode: '0755'
  register: rclone__register_facts

```

When executing the role, I get:
```
TASK [stefangweichinger.ansible_rclone : Create directory for ansible custom facts] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "There was an issue creating /etc/ansible/facts.d as requested: [Errno 13] Permission denied: b'/etc/ansible/facts.d'", "path": "/etc/ansible/facts.d"}
```

The solution would be to add `become: true` in both tasks.
