### ISSUE TITLE
New to ansible, help me with my YML?

### ISSUE THREAD

**Issue by clupss** [stefangweichinger/ansible-rclone#111]
Hi there,
New to ansible.
I got rclone installing fine.
However I am trying to configure my gdrive remote

My YML is as follows:

```
- name: rClone Google Drive installer & configurator
  hosts: gdrive
  become: true
  roles:
    - rclone
      rclone_config_location: /etc/ansible/playbooks/rclone.conf
      rclone_configs:
        - name: google
          properties:
            type: drive
            client_id: --REDACTED--
            client_secret: --REDACTED--
            scope: drive
            token: ' {"access_token":"--REDACTED--","token_type":"Bearer","refresh_token":"--REDACTED--","expiry":"--REDACTED--"}'
            team_drive: --REDACTED--
```

The problem I have is that when I run this, I get a YAML error syntax.
```
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/etc/ansible/playbooks/rclone.yml': line 7, column 29, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - rclone
      rclone_config_location: /etc/ansible/playbooks/rclone.conf
                            ^ here
```

I cannot figure out how to define the rclone_configs in the playbook, in a way that it accepts. 

I was wondering if someone could help!

Thanks
