### ISSUE TITLE
Request: add semantic versioning tags and releases to project

### ISSUE THREAD

**Issue by arrrgi** [stefangweichinger/ansible-rclone#123]
Hi @stefangweichinger 

Just an idea that will probably help folks using your great role. I think it would be useful learning experience to setup semantic versioning and releases with tags and a Github action for your repo.

@geerlingguy (who I note uses your role too) has an existing config you might consider re-using to do the same.

This helps us folks who import and lock specific versions of roles that are known to work in our own projects from Galaxy, ie.

```yaml
# requirements.yml
# Install dependency roles from Galaxy
- src: geerlingguy.docker
  version: 6.0.4
- src: geerlingguy.pip
  version: 2.2.0
- src: stefangweichinger.ansible_rclone
#  version: x.x.x
```
