### ISSUE TITLE
Rclone config default location

### ISSUE THREAD

**Issue by Hongbo-Miao** [stefangweichinger/ansible-rclone#138]
I installed Rclone by

```yaml
- name: Install Rclone
  hosts: hm-ubuntu
  roles:
    - role: stefangweichinger.ansible_rclone
      vars:
        rclone_arch: arm64
        # rclone_config_location: "{{ ansible_env.HOME }}/.config/rclone/rclone.conf"
        rclone_configs:
          - name: hm-s3
            properties:
              type: s3
              provider: AWS
              access_key_id: xxx
              secret_access_key: xxx
              region: us-west-2
              storage_class: STANDARD
```

However, after installing, Rclone cannot find the config I added expects to read the config at default location `~/.config/rclone/rclone.conf` (`/home/parallels/.config/rclone/rclone.conf` in this case)

```shell
parallels@ubuntu-linux-22-04-desktop:/usr/bin$ which rclone
/usr/local/bin/rclone

parallels@ubuntu-linux-22-04-desktop:/usr/bin$ ls -l /usr/local/bin/rclone
-rwxr-xr-x 1 root root 48037888 Jul 17 06:48 /usr/local/bin/rclone

parallels@ubuntu-linux-22-04-desktop:/usr/bin$ rclone config file
Configuration file doesn't exist, but rclone will use this path:
/home/parallels/.config/rclone/rclone.conf

parallels@ubuntu-linux-22-04-desktop:/usr/bin$ rclone config
2023/08/11 15:01:34 NOTICE: Config file "/home/parallels/.config/rclone/rclone.conf" not found - using defaults
No remotes found, make a new one?
n) New remote
s) Set configuration password
q) Quit config
n/s/q> 
```

Because **ansible-rclone** installed the config file at `/root/.config/rclone/rclone.conf`:

```shell
parallels@ubuntu-linux-22-04-desktop:/usr/bin$ sudo cat /root/.config/rclone/rclone.conf
[sudo] password for parallels: 
[hm-s3]
type = s3
provider = AWS
access_key_id = xxx
secret_access_key = xxx
region = us-west-2
storage_class = STANDARD
```

I know I can use `rclone_config_location: "{{ ansible_env.HOME }}/.config/rclone/rclone.conf"` to change to default path Rclone expects. And also need use `rclone_config_owner` to change to non-root user so that Rclone can read.

However, I am thinking should we use `~/.config/rclone/rclone.conf` as default location? Thanks! 😃
