### ISSUE TITLE
Installation not idempotent

### ISSUE THREAD

**Issue by devster31** [stefangweichinger/ansible-rclone#172]
Hello,
I'm running into a minor issue with the role, specifically when run twice in a row it still returns some changed tasks.
Some information below.

Control machine:
```
ansible [core 2.18.0]
  config file = /<user_home>/.ansible.cfg
  configured module search path = ['/<user_home>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /<user_home>/code/infrastructure/dispenser/.venv/lib/python3.13/site-packages/ansible
  ansible collection location = /<user_home>/.ansible/collections:/usr/share/ansible/collections
  executable location = /<user_home>/code/infrastructure/dispenser/.venv/bin/ansible
  python version = 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.4)] (/<user_home>/code/infrastructure/dispenser/.venv/bin/python3.13)
  jinja version = 3.1.4
  libyaml = True
```

Remote machine:
```
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```
Running the rclone fact file after first run:
``` 
$ /etc/ansible/facts.d/rclone.fact
{
    "configured": true,
    "installed": true,
    "installed_version": "1.68.2"
}
```
Specific tasks which are always flagged as `changed`:
```
TASK [stefangweichinger.ansible_rclone : Update repositories cache on Ubuntu] *********************************************************************************************************************
changed: [remote]

...

TASK [stefangweichinger.ansible_rclone : Remove temporary working directory] **********************************************************************************************************************
changed: [remote]

```
I believe this should not happen.

**Comment by stefangweichinger** [comment]
Thanks for reporting. Quite busy these days and ready for vacation ... so pls allow some delay before I can look into this closer.

As always: PRs welcome ;-)

**Comment by stefangweichinger** [comment]
updating the apt cache is always a change, I think ...

We could set https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-cache_valid_time to make it "more idempotent": only update the cache if it's older than an hour or something.

For the temporary directory: suggestions welcome. I'd have to research how to handle this better.

**Comment by devster31** [comment]
From what I remember using `ansible.builtin.apt` circumvents the problem, maybe splitting the install like so would make it run smoothly.

```yaml
- name: Update repositories cache on Debian OS family
  ansible.builtin.apt:
    name: '{{ item }}'
    update_cache: true
  loop: '{{ rclone_packages }}'
  when: >-
    rclone_packages | length > 0
    and ansible_facts.os_family == 'Debian'

- name: Install required packages
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop: '{{ rclone_packages }}'
  when: >-
    rclone_packages | length > 0
    and ansible_facts.os_family != 'Debian'
```

For the working directory I believe the issue is that the flow deletes it before installation but not after it, so the second run finds a temporary directory to delete.
I believe one solution could be remove it also at the end of the installation flow.
