### ISSUE TITLE
Config folder should be created

### ISSUE THREAD

**Issue by m3nu** [stefangweichinger/ansible-rclone#40]
This folder may not exist and the role should make sure it exists:

`FAILED! => {"changed": false, "checksum": "8dfd770af55b0c932bd63e7d26f01b93e6faf9f2", "msg": "Destination directory /root/.config/rclone does not exist"}`

E.g. (untested)
```
- name: Create rclone config directory
  file: path='{{ rclone_config_location }}' state=directory mode=0700

- name: Set up rclone config
  template:
    src: rclone.conf.j2
    dest: '{{ rclone_config_location }}'
  when: rclone_configs is defined
```
