### ISSUE TITLE
rclone_configs breaks when properties have json objects

### ISSUE THREAD

**Issue by Gordin** [stefangweichinger/ansible-rclone#45]
I have this in one of my playbooks:
```yaml
  vars:
    rclone_arch: "arm"
    rclone_config_location: "/home/pi/.config/rclone/rclone.conf"
    rclone_configs:
      - name: pCloud
        properties:
          type: pcloud
          token: {"access_token":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}
```
using the playbook works, but this is what tho rclone config file looks like afterwards:
```
[pCloud]
type = pcloud
token = {'access_token': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'token_type': 'bearer', 'expiry': '0001-01-01T00:00Z'}
```
This results in an error message when trying to ls the remote, because rclone can't read the token. Ansible seems to have parsed the token to an object and serializes it later with single quotes instead of double quotes. I guess the fix would just be to make Ansible interpret the variables as strings, I don't know Ansible though, so I don't know if that's possible.

My workaround is to just put single quotes around the token variable like this:
```
token: '{"access_token":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}'
```

This seems to work, Ansible does not touch the formatting anymore and rclone can connect to the remote afterwards. If fixing this is not possible due to how Ansible reads config files, it would be nice if you could add single quotes to the variables in the README.md, because right now your example will break.
