### ISSUE TITLE
Can't install specific version of rclone

### ISSUE THREAD

**Issue by mjmayer** [stefangweichinger/ansible-rclone#68]
The README.me indicates that the variable `rclone_version`, is not set by default, but can be defined as `stable`, `beta` or a specific version. But the logic in `tasks/main.yml` don't support the specific version option.

```yaml
- name: Do stable install
  include_tasks: stable.yml
  when:
    - rclone_version is undefined or
      rclone_version == 'stable' or
      rclone_version != 'beta'

- name: Do beta install
  include_tasks: beta.yml
  when: rclone_version == 'beta'
```
