### ISSUE TITLE
Config file permissions seem too lenient

### ISSUE THREAD

**Issue by theenglishway** [stefangweichinger/ansible-rclone#86]
Yet another much more important issue that comes up while reading the code following issue #84 

```
- name: Set up rclone config
  template:
    src: rclone.conf.j2
    dest: '{{ rclone_config_location }}'
    mode: 0644
  when: rclone_configs is defined
```

It seems to me like the permissions are way off, and should instead be 0600.. 

This is what the rclone.conf file permissions look like when you go through the `rclone config` interactive process on a brand new installation :

```
root@debian-server:~# ls -l /root/.config/rclone/
total 4
-rw------- 1 root root 21 Mar 21 16:37 rclone.conf
```

I'm almost surprised `rclone` does not issue a warning or even an error when that file is readable by anyone else than the user, since it holds some pretty interesting secrets..
